Task 3
LeonidShatilo/react-app pull request #3
Opened 2021-04-21 21:10 UTC by LeonidShatilo

### Task:
Based on your 2nd task, make an additional opportunity to create and delete cards (for cards I mean any array of objects with image and description, for example, `const cards = [{ id: 1, category: 'male', imgUrl: '', price: 100 }])`.

### Requirements:
- Rewrite all classes components to functional components with hooks.
- Each `<Card />` component could be deleted from catalogue by clicking on the cross button (❌) which can be placed somewhere on the top of each card. After clicking on the button the array of cards in your `<CardsContainer />` should be updated.
- `<CardsContainer />` component should also additionally render `<CardsCreationForm />` as its children. This form should contain all the required inputs for creating the card (find a way on how to use only 1 handler for all the inputs) and a submit button. By clicking on a submit button the array of cards in your `<CardsContainer />` should be updated with the new card data.
- All the required handlers for creating/deleting cards should be in the `<CardsContainer />` component and passed down to child components as props.

2021-04-26 19:55 UTC, broshkabro requested changes
There is an issue when I click submit button
![image](https://user-images.githubusercontent.com/18407086/116142326-72932e00-a6e2-11eb-832a-81330ed8c07e.png)

2021-04-26 19:55 UTC, broshkabro commented on src/components/Cards/CardsCreationForm/CardsCreationForm.js
> +          onChange={(event) => handleChange(event, key)}
I reckon that for this app it is better to catch all input values on submit. `onChange `event leads to unnecessary re-render every time a user types something.

2021-04-27 12:46 UTC, LeonidShatilo commented on src/components/Cards/CardsContainer/CardsContainer.js
> +    const cards = [...cardData.cards];
You're right! Removed.

2021-04-27 12:47 UTC, LeonidShatilo commented on src/components/Cards/CardsCreationForm/CardsCreationForm.js
> +          onChange={(event) => handleChange(event, key)}
Implemented.

2021-04-27 12:49 UTC, LeonidShatilo commented
> There is an issue when I click submit button
> ![image](https://user-images.githubusercontent.com/18407086/116142326-72932e00-a6e2-11eb-832a-81330ed8c07e.png)

I'm fixed this issue.

2021-04-29 20:15 UTC, merged