Task 5
LeonidShatilo/react-app pull request #5
Opened 2021-05-11 14:27 UTC by LeonidShatilo

### Task: 
Based on your previous tasks, add 3 routes to your application: login page (`/login`), your profile page (`/profile`), and your page with cards (`/cards`).
 
### Requirements:
- Your app should redirect the user to a login page (`/login`). You can do it using the history API from react-router. On this login page create a form with 2 inputs (username and password) with a submit button (use mocked logic for login).
- If the user successfully logged in, he can be able to view the profile (`/profile`) page and cards (`/cards`) page.
- Profile page contains any data you like. (Add 2-3 sentences about yourself).
- Cards page should contain your <CardsContainer /> component with all the logic you’ve done before (no additional code required).

**Important note:** If the user is not logged in he should **NOT** able to view `/profile` and `/cards` pages.

2021-05-13 21:19 UTC, broshkabro requested changes
Looks awesome in general. Please fix the way you work with `setTimeout `function.

2021-05-13 21:19 UTC, broshkabro commented on src/components/App/App.js
> +
`setTimeout ` is a [side-effect function](https://dmitripavlutin.com/react-useeffect-explanation/) and it should be implemented in `useEffect `hook

2021-05-13 21:19 UTC, broshkabro commented on src/components/App/App.js
> +      </Switch>
This is an acceptable way of protecting routes, however, I reckon that it would be better to create a wrapper for each route that will be responsible for giving/not giving access to the app. The check itself should happen before a user loads the corresponding component.
_P.S. This suggestion is optional._

2021-05-14 20:11 UTC, LeonidShatilo commented on src/components/App/App.js
> +
Unfortunately, I was unable to implement this, so I removed `setTimeout`. But I will be sure to keep that in mind for the future, thanks!

2021-05-14 20:12 UTC, LeonidShatilo commented on src/components/App/App.js
> +      </Switch>
I considered your suggestion and decided to implement it.

2021-05-17 08:14 UTC, broshkabro approved these changes

2021-05-17 08:19 UTC, merged